"""initial schema

Revision ID: 84d0c02133b7
Revises: 
Create Date: 2026-07-16 16:54:40.979336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84d0c02133b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wa_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('shop_name', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('checkin_hour', sa.Integer(), nullable=True),
    sa.Column('last_checkin_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('convo_state', sa.Enum('NEW', 'ONBOARDING_NAME', 'ONBOARDING_ITEMS', 'ONBOARDING_CHECKIN_TIME', 'IDLE', 'AWAITING_ITEM_CONFIRM', 'AWAITING_SALE_CONFIRM', 'AWAITING_RESTOCK_CONFIRM', 'AWAITING_GUARDIAN_CONSENT', name='convo_state'), nullable=False),
    sa.Column('pending_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('checkin_hour IS NULL OR (checkin_hour >= 0 AND checkin_hour <= 23)', name='ck_users_checkin_hour_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_wa_id'), 'users', ['wa_id'], unique=True)
    op.create_table('guardian_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('guardian_wa_id', sa.String(length=20), nullable=False),
    sa.Column('guardian_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('digest_freq', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'guardian_wa_id', name='uq_guardian_owner_wa')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('cost_kobo', sa.Integer(), nullable=True),
    sa.Column('price_kobo', sa.Integer(), nullable=False),
    sa.Column('low_stock_at', sa.Integer(), nullable=False),
    sa.Column('low_stock_alerted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_kobo >= 0', name='ck_items_price_nonneg'),
    sa.CheckConstraint('qty >= 0', name='ck_items_qty_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_items_user_name')
    )
    op.create_index(op.f('ix_items_user_id'), 'items', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wamid', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('msg_type', sa.String(length=20), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wamid')
    )
    op.create_index(op.f('ix_messages_processed_at'), 'messages', ['processed_at'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_kobo', sa.Integer(), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_wamid', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_user_sold', 'sales', ['user_id', 'sold_at'], unique=False)
    op.create_table('sale_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price_kobo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_lines_sale_id'), 'sale_lines', ['sale_id'], unique=False)
    op.create_table('stock_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INITIAL', 'SALE', 'RESTOCK', 'ADJUSTMENT', name='stock_move_type'), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moves_item_created', 'stock_moves', ['item_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_moves_item_created', table_name='stock_moves')
    op.drop_table('stock_moves')
    op.drop_index(op.f('ix_sale_lines_sale_id'), table_name='sale_lines')
    op.drop_table('sale_lines')
    op.drop_index('ix_sales_user_sold', table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_messages_processed_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_items_user_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('guardian_links')
    op.drop_index(op.f('ix_users_wa_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
