"""storefront slug + owner weekly summary

Revision ID: 922146ebdfac
Revises: 92b8735712c5
Create Date: 2026-07-18 09:24:57.594774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922146ebdfac'
down_revision: Union[str, Sequence[str], None] = '92b8735712c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slug', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('weekly_summary_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'weekly_summary_sent_at')
    op.drop_column('users', 'slug')
    # ### end Alembic commands ###
