"""guardian link columns

Revision ID: 92b8735712c5
Revises: 84d0c02133b7
Create Date: 2026-07-18 02:24:25.825989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b8735712c5'
down_revision: Union[str, Sequence[str], None] = '84d0c02133b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardian_links', sa.Column('invite_code', sa.String(length=16), nullable=True))
    op.add_column('guardian_links', sa.Column('digest_sent_at', sa.DateTime(), nullable=True))
    op.alter_column('guardian_links', 'guardian_wa_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'guardian_links', ['invite_code'])
    op.add_column('users', sa.Column('quiet_alerted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'quiet_alerted')
    op.drop_constraint(None, 'guardian_links', type_='unique')
    op.alter_column('guardian_links', 'guardian_wa_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('guardian_links', 'digest_sent_at')
    op.drop_column('guardian_links', 'invite_code')
    # ### end Alembic commands ###
